version: '3'

services:
  backend:
    build: ./backend 
    container_name: 'backend'
    command: npm run start:dev
    restart: always
    volumes:
      - ./backend:/app/backend/src
    ports:
      - 3000:3000
    environment:
      - PRODUCER_PORT=3000
      - CLIENT_PORT=5672
      - USER=user
      - PASSWORD=user
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net

  microservice:
    build: ./microservice 
    container_name: 'microservice'
    command: npm run start:dev
    restart: always
    volumes:
      - ./microservice:/app/microservice/src
    ports:
      - 3001:3001
    environment:
      - CONSUMER_PORT=3001
      - CLIENT_PORT=5672
      - USER=user
      - PASSWORD=user
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net

  rabbitmq:   
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    networks:
      - rabbitmq_go_net
  
networks:
  rabbitmq_go_net:
    driver: bridge

